version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file: .env  

  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file: .env  
    environment:
      - MONGO_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/voice_auth_db?authSource=admin
    volumes:
      - ./voices:/app/voices

volumes:
  mongodb_data: